### ISSUE TITLE
Example app that doesn't use React?

### ISSUE THREAD

**Issue by tomardern** [contentful/apps#110]
Hi,

Is there an example app that doesn't use React?

Thanks,

**Comment by davidfateh** [comment]
Hi @tomardern,

We currently do not have any other example apps besides React apps. There are a few reasons for this but before I go into them, I would like to clarify that **you don't need to use React to build an app for Contentful**.

While we are biased towards React, we know that not everyone is using it and we don't want to disallow any contributions to this repo because of that. Our [UI-SDK](https://github.com/contentful/ui-extensions-sdk) is library/framework agnostic and can feasibly be implemented into apps built with Angular, Vue, JQuery, or any other (or lack of) lib/framework.

However, there are a few benefits to using React. One of the major benefits is [Forma-36](https://github.com/contentful/forma-36), a design system with pre-built React components that allows developers to build UIs which talk seamlessly with our design language. All common components and functionality found within Contentful are almost always built with Forma-36 which means you can spend less time worrying about how your UI will functionally work and instead spend that time working solely on your bespoke business logic. We regularly update and maintain Forma-36 so you can be assured it will always be up to date.

Another reason why we use React is [create-contentful-app](https://github.com/contentful/create-contentful-app), a CLI tool which will bootstrap a React app with all available [app locations](https://www.contentful.com/developers/docs/extensibility/app-framework/locations/). Again, this helps you spend less time setting up and more time getting to your business logic.

I hope this answer is helpful and feel free to follow up with any questions you may have.

**Comment by tomardern** [comment]
Thanks David for such a clear and great response :)
