### ISSUE TITLE
Unable to view Media Library with Safari

### ISSUE THREAD

**Issue by tpiros** [contentful/apps#1162]
**Describe the bug**
I'm trying to open the Media Library widget on Safari but I can't get past the authentication step. See attached video.

**To Reproduce**
1. Create a content model and configure the Cloudinary app
2. Try to add new content - click on "Select or upload a file on Cloudinary"
3. Enter endless loop

**Expected behaviour**
Should be able to see images from the Cloudinary Media Library

**Screenshots**
[If applicable, add screenshots to help explain your problem.
](https://user-images.githubusercontent.com/2042718/164587212-2ae4a85e-f602-4311-8995-37c7cb93fc80.mp4
)

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.3.1
 - Browser Safari
 - Version 15.4

**Comment by andipaetzold** [comment]
Hey @tpiros ,

I was able to reproduce your issue in Safari and Brave. Everything seems to work in Google Chrome, so you can use that in the meantime to get unblocked.
We'll work on a fix to make the Cloudinary app work again in Safari.

**Comment by andipaetzold** [comment]
I did some research and the issue seems to be on Cloudinary's side. Safari blocks cross-site cookies by default and therefore the authentication does not properly work. Here is a three year old thread in their support forum: https://support.cloudinary.com/hc/en-us/community/posts/360006487280-Media-Library-Widget-has-stopped-working

The "solution" is to disable the "Prevent cross-site tracking" setting in Safari. This is obviously not ideal, but I think there is nothing we can change about our app to make this work.

I'd therefore also close this issue.
