### ISSUE TITLE
Optional fields when creating Mux Assets

### ISSUE THREAD

**Issue by s23h** [contentful/apps#1467]
Examples include: Watermarks, Audio Normalisation, Enabling MP4 as seen in the Mux Docs here

https://docs.mux.com/guides/video/add-watermarks-to-your-videos

https://docs.mux.com/guides/video/adjust-audio-levels

https://docs.mux.com/guides/video/enable-static-mp4-renditions

**Comment by blairliikala** [comment]
Hey there! These are great suggestions.  Would you be able to explain a little more how you would use them?  If we were to add audio normalization and mp4 renditions, would it be more ideal to make those global settings like signed playback, or an option in each field?

**Comment by s23h** [comment]
Hi! When we currently upload videos, we use a lambda to enableMp4 for every video as we also require the videos in mp4 format, so for that, a global option would make sense.

Audio normalisation however can only be done on asset creation, so we are currently unable to do this even though we’d like to (we require a uniform viewing experience for the content). For this, I also think a global option makes the most sense.

Thanks!

On 22 Jul 2022, at 01:02, Blair ***@***.******@***.***>> wrote:



Hey there! These are great suggestions. Would you be able to explain a little more how you would use them? If we were to add audio normalization and mp4 renditions, would it be more ideal to make those global settings like signed playback, or an option in each field?

**Comment by blairliikala** [comment]
Thanks! Audio and mp4s should be fairly quick to implement, so I can get those on the list to add. Watermarking would take more time, and we would like to tackle caption/subtitles before that.

**Comment by isaac-martin** [comment]
Hey @blairliikala - regarding captions, should i store these now as a separate file in contentful? Or will i need to use the mux api to upload a track?

**Comment by blairliikala** [comment]
You should use the Mux API and send captions/subtitles to Mux so they can be embedded and displayed in the player.  Storing them in also Contentful would be useful for other features like searching text tracks.

**Comment by isaac-martin** [comment]
@s23h Intetested in how you enable mp4 via lamba? I need this also. Assume its just a webhook to an api route?

**Comment by blairliikala** [comment]
A quick update.  I have a POC of adding captions, and also includes the audio normalization, and some other bits.  Right now captions would need a URL to the file, and that could come from a copy/paste URL through Contentful's file manager, or externally like S3, Dropbox...etc.

Mp4 and also master files can take a little while to process.  Normally apps listen for Mux's webhooks to notify and update when those operations are finished.  However because Contentful isn't able to be setup this way, the current app has to poll for updates.  While we could have mp4s be generated at the time of upload, getting a response back into Contentful is problematic.  The user would have to leave the browser window open for polling to happen.  If they left and came back, then data would be be in various states.  We currently see this with uploading with non-standard files needing to take awhile to re-process.  For now I think the mp4 is on pause until we can find a better way to handle this, but open to suggestions and feedback!

**Comment by s23h** [comment]
Amazing, cheers. Will give it a go.

On 26 Sep 2022, at 16:27, Blair ***@***.***> wrote:

﻿

@isaac-martin<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fisaac-martin&data=05%7C01%7C%7C4fee981a855d4e3fbb6808da9fd39cba%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637998028458281624%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bXIWWbgw%2BReC5F9pYq00k3mwQevcIWeblxQDHnIYx1g%3D&reserved=0> @s23h<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fs23h&data=05%7C01%7C%7C4fee981a855d4e3fbb6808da9fd39cba%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637998028458281624%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3xZ2J0tYRFOtXebJpz6POnzI0LyUdthSD2sV%2FqiyKTI%3D&reserved=0> Update released includes audio normalization and closed captions. Let me know how it works! We are waiting on mp4/master creation for now until we can work out the issue mentioned above.

**Comment by mgoudy91** [comment]
Marking this issue as closed. Let us know if you need anything else.
