### ISSUE TITLE
Cloudinary addon is not pulling image metadata information

### ISSUE THREAD

**Issue by electriccode** [contentful/apps#172]
**Describe the bug**
Cloudinary image has structural, contextual and embedded metadata types and none of those aren't returned when using contentful Apis to get the entry. There is a metadata field returned which is always an empty array.
**To Reproduce**
1. Create a content model with a Cloudinary field
2. Create some entries and upload some Cloudinary images
3. Add some metadata to the above Cloudinary images, eg add description field in contextual metadata
4. Get the entries for the content model and check metadata field for the Cloudinary image field in JSON output

**Expected behavior**
The metadata should return contextual metadata. Ideally this field should be an object like this
```json
{
  "structural": {
    "product_engagement": "value"
  },
  "contextual": {
    "title": "title",
    "description": "description which can be used as an alt tag"
  },
  "embedded": {
    "Colorspace": "rgb",
    "DPI": "96"
  }
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1471581/103620209-1f417800-4f59-11eb-94b6-a8a3cc33e3f4.png)
![image](https://user-images.githubusercontent.com/1471581/103620701-f8d00c80-4f59-11eb-8ae9-58d7bd28c035.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: MS Edge
 - Version: 86.0.622.48

**Cloudinary settings**
- Strict transformations enabled
- Usage of tags/context/metadata in transformation URLs: enabled

**Comment by andipaetzold** [comment]
Hey @electriccode,

This is actually the expected behavior of our Cloudinary App. Because the App runs inside the contentful Frontend, it isn't able to respond to updates in Cloudinary metadata. This means that the data that is inserted by the App is set at the time when it is inserted.

To store Cloudinary's metadata in Contentful, you have to edit the images within Cloudinary first and only then insert them into Contentful using the App.

**Comment by electriccode** [comment]
Thankyou @andipaetzold for prompt reply. I tested that out. Closing this.
