### ISSUE TITLE
Typeform App 403 error

### ISSUE THREAD

**Issue by code-by-gijs** [contentful/apps#3314]
**Describe the bug**
After installing the Typeform app and authorizing my account I cannot select any of my Typeform workspaces. The workspaces do exist in my account but the Contentful Typeform app returns a 403 while fetching the Typeform workspaces

**To Reproduce**
Try installing the Typeform app

**Expected behavior**
I would expect to see a dropdown with my Typeform workspaces

**Screenshots**
![Screenshot 2023-04-26 at 14 59 27](https://user-images.githubusercontent.com/1674627/234582623-f1d8e1cb-b9e5-41bd-8e58-ed2619776413.png)
![Screenshot 2023-04-26 at 15 00 08](https://user-images.githubusercontent.com/1674627/234582628-6813c5e4-6a5a-46ef-86c4-d62423afc1f2.png)
![Screenshot 2023-04-26 at 15 00 16](https://user-images.githubusercontent.com/1674627/234582633-4ed9a9b6-907c-4935-986d-0b298a35eef9.png)

**Desktop (please complete the following information):**
 - OS: MacOS 13.3.1
 - Browser: Firefox
 - Version 112.0.1

**Additional context**
-

**Comment by lilbitner** [comment]
Hello @code-by-gijs thank you for bringing this to our attention. Currently I am able to successfully retrieve workspaces when using this app, so am not able to replicate this issue. Since you were able to successfully login to your Typeform account, and given the 403 Forbidden error, I am wondering if this might be a permissions issue within Typeform itself. Do you mind checking to make sure you have correct permissions to retrieve the Typeform workspaces? Thank you in advance! I am sure we can get to the bottom of it 😄

**Comment by whitelisab** [comment]
Hi @code-by-gijs, we are going to close this issue because it has become stale. Please feel free to open another issue if you are still experiencing problems!
