### ISSUE TITLE
Allow regex for contentTypes option for selectSingleEntry

### ISSUE THREAD

**Issue by knynkwl** [contentful/apps#4265]
There are only certain content types in our app that have slugs, thus when selecting an entry type, instead of listing all the static values, it would be great if there was a way to regex them to get them all.

Instead of this:
```js
sdk.dialogs.selectSingleEntry({
  contentTypes: ['pageProduct', 'pageHome', 'pageBasic'],
})
```
Something like this would be helpful:
```js 
sdk.dialogs.selectSingleEntry({
  contentTypesRegex: /^page.*$/,
})
```

**Comment by ghepting** [comment]
Hey @knynkwl thanks for reaching out. This is a great idea for improved developer experience, but because of how our API works, this isn't something we could currently support. I'll close this issue for now, but definitely send a couple of our PMs a note since this would be very convenient! Thank you again for taking the time to send this feedback, it really helps us prioritize the work our teams do and improve our platform!

**Comment by ghepting** [comment]
Also, just for clarification, this issue should have actually been created under the https://github.com/contentful/ui-extensions-sdk repository where the app SDK source code lives! 😄
