### ISSUE TITLE
Commercetools APP - Selected Product name for the locale defined in the app setup not shown

### ISSUE THREAD

**Issue by Engerim** [contentful/apps#55]
In this file is a handlebar template set which uses "name.en" to show the product name of a product. But we don't have this locale so nothing shows up. I think it is better to use the defined locale from the app setup. 

https://github.com/contentful/apps/blob/7e1e3df4deebb75ece0f232af4279e6b7b3f7cab/apps/commercetools/src/vendor/ct-picker.min.js#L8718

**Comment by Engerim** [comment]
@gmenoiaa

**Comment by davidfateh** [comment]
@giotiskl would you mind taking a look at the file in question and giving some more background information on how it was produced? It appears this is a vendor script which we necessarily may not want to change ourselves.

**Comment by giotiskl** [comment]
@Engerim excuse my late reply. Thank you for raising the issue, we will be looking into it.

**Comment by Engerim** [comment]
okay thanks

**Comment by Engerim** [comment]
@giotiskl is there any news? as it is still not working

**Comment by davidfateh** [comment]
Hi @Engerim. I believe this issue is quite old at this point. Are you still experiencing this? It appears that the code in question is provided by commercetools which means if the issue still stands, you may have to open a ticket with them to inspect their vendor code and make the appropriate changes.

Let me know if you have any questions. I'm going to close this issue for now but feel free to re-open if you think there is still something to be discussed.
