### ISSUE TITLE
Cloudinary app builds thumbnail URLs using the default 'type' (upload) and therefore thumbnails don't display for assets of type 'private'

### ISSUE THREAD

**Issue by aleksandar-cloudinary** [contentful/apps#58]
When building the Cloudinary URL in `makeThumbnail` only the public_id and thumbnail transformation string are passed into the `url` and `video_thumbnail_url` functions.

In Cloudinary an asset is unique/identified by not only the public_id but only when in combination with the 'resource_type' and 'type'. Therefore the below assets with the same public_id (sample) are actually different entities:

```
image/upload/sample
image/private/sample
video/upload/sample
```

As the 'type' parameter isn't supplied Cloudinary defaults it to 'upload'. This works for most cases but when one of the selected assets is not of type 'upload' then the URL will be built incorrectly and therefore the requested thumbnail would not be returned.

We have a client who has images uploaded as private and therefore currently the thumbnails don't display.

I've made a small change to the code locally but have no permission to push it to a branch and therefore create a pull request.

What's the procedure for submitting PRs?

**Comment by davidfateh** [comment]
Hi @aleksandar-cloudinary, thanks for submitting an issue. It sounds like you have already made a code change which could potentially be a fix. We'd love to take a look!

In order to submit a PR to this repo, you need:
1. Fork the repo.
2. Create a branch with your change.
3. Submit a PR in your fork back to this repo.

For more information on how to do this in GitHub, please see their [documentation](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by aleksandar-cloudinary** [comment]
Thanks, @davidfateh. I've added a PR.
