### ISSUE TITLE
Instance parameters for App (Cloudinary)?

### ISSUE THREAD

**Issue by dufkaf** [contentful/apps#70]
Hello. Instance parameters are documented for UI extensions e.g. [here](https://www.contentful.com/developers/docs/extensibility/ui-extensions/sdk-reference/#configuration-of-an-extension-with-parameters) or [here](https://www.contentful.com/developers/docs/tutorials/general/uiextensions-configuration/)
I was searching how to do same for App but didn't find any documentation about this and from the code examples and implementation it looks like it is not there (at all?). E.g. [this commit](https://github.com/contentful/apps/commit/25d9a9d9282d8810509d9b660560debf654a327f)  takes care of migrating installation parameters from extension.json but instance parameters are not handled/migrated there. What is the status with this?

I'd like to have some settings per field. With Cloudinary integration I'd like to have per field settings of 
- initial folder
- max count of assets or multiselect bool flag - currently it is always an array, for some fields it makes sense to link just one image and then the json don't need to be an array
- asset type filter - e.g. image field vs video field

**Comment by dufkaf** [comment]
btw found original cloudinary integration by @michelbitter which was still done as extension and all the settings are of "instance" type [there](https://github.com/michelbitter/extensions/blob/master/marketplace/cloudinary-assets/extension.json), at least the maxFiles with default value 1 makes better sense like this instead of being global setting now.

**Comment by dufkaf** [comment]
Not sure why github now shows @davidfateh linked a pull request that will close this issue. As this should not close it, this is about instance parameters i.e. one set per each content type, that pull request won't solve it, it only adds **installation** parameter for starting folder, not instance one.

**Comment by davidfateh** [comment]
I originally linked this PR because it would close out your first bullet point which is the initial folder. The other bullet points you mentioned are things we haven't considered yet. I've unlinked the PR for now so it won't close this issue.

Currently, as we work on the app framework, we have to divert some of our efforts to focusing on building out the underlying infrastructure. For these reasons we cannot always commit to building new features in the existing apps at the current time. We do plan to revisit the issues in the future but also welcome outside contributors to submit PRs with functionality they deem useful.

That being said, I believe functionality you are looking for is possible to implement but it would require customizing how the configuration screen inside of the app functions. You could, in theory, change the configuration screen to have even further customization on a per entry field basis.

**Comment by dufkaf** [comment]
> Currently, as we work on the app framework, we have to divert some of our efforts to focusing on building out the underlying infrastructure.

Makes perfect  sense, so allowing instance parameters again is 'building out underlying infrastructure' ?

> You could, in theory, change the configuration screen to have even further customization on a per entry field basis.

I know how it worked with extensions. And it almost works like this with apps. You go to properties->appearance of specific  field and pick Cloudinary app as appearance. On the same screen you could add instance parameters for extensions but not so for apps now. There is just empty space on the botom.
![image](https://user-images.githubusercontent.com/1853026/78784445-a3a0a380-79a5-11ea-9981-22ca1bfe5e3f.png)
 
Yes I noticed you see fields linked to this app in app configuration screen but this is not primary way to link them (?) so the settings should probably be not there too. Even now you link them via appearance screen so instance parameters make best sense to be set there too like it was with extensions. Or maybe you are going this way? To kill the appearance selection for apps and do everything on app configuration screen?

> For these reasons we cannot always commit to building new features in the existing apps at the current time.

Sure, we are currently hosting this customized extension ourselves, I am just sending changes upstream. I do not expect you to develop new features to Cloudinary app yourself. But I hope accepting such pull request is OK.

**Comment by davidfateh** [comment]
Hey @dufkaf,

I've discussed this situation with the team and we definitely see the value of having instance parameters added into apps as well. We are going to add that work to our backlog. 

In the meantime I can offer you a workaround since you did mention you are running the customized version privately.

The workaround would be to customize the app's configuration screen to save additional information in the installation parameters about your selected fields. Then in the field component, you would read the app's installation parameters and see if there are any customizations you need to make to the field.

I hope this is helpful to you.

**Comment by davidfateh** [comment]
Going to close this issue for now. Like mentioned above, the workaround is to save various settings into installation parameters.

**Comment by DaniRey** [comment]
Hey @davidfateh 

Although there is a workaround, it would be great if you could keep that issue open until instance parameters are implemented. This allows interested people to watch the issue and update their apps, as soon as the feature is available.

**Comment by Grizzlien** [comment]
So is this an issue in general for apps? Apps does not support instance parameters, only extensions? Or did I missunderstand?
I'm also having trouble reading the instance parameters of an app. If I set default values in the app definition, sure they show up, but not the overrides set on the actual field.

**Comment by fabe** [comment]
@Grizzlien Hey! Apps fully support instance parameters: https://www.contentful.com/developers/docs/extensibility/app-framework/instance-parameters/

If you have a problem with them, please open another issue or ask a question in our [community Slack](https://www.contentful.com/slack/) so our engineers can help you out :)

**Comment by Grizzlien** [comment]
@fabe 

Maybe it's just when you use the dam-app-base it´s tricky? Maybe that base doesn´t support it. 
Thanks I'll check it out
