### ISSUE TITLE
Content Generator: SEO Character Limits

### ISSUE THREAD

**Issue by allanwhite** [contentful/apps#8813]
### Description
The SEO defaults in the AI Content Generator App do not follow [length guidelines](https://www.contentful.com/seo-guide/on-page-seo/#meta-description), causing prompts to return generated SEO descriptions that are too long. 

### To reproduce
Use the AI Content Generator App to generate an SEO meta description. This does not impact other features such as translating one field to another language. 

### Expected behavior
From the Contentful SEO guide: 
> Ideally, [descriptions must be] be between 100 and 150 characters in length to avoid truncation in search results.

### Proposed solution
Modify the values in the prompt parameters [here](https://github.com/contentful/apps/blob/master/apps/ai-content-generator/src/prompts.ts#L6) and [here](https://github.com/contentful/apps/blob/b92ef96b77aadf4319755ec06435a5255e7d91b1/apps/ai-content-generator/src/configs/prompts/seoDescriptionPrompt.ts#L2) to be `150`. 

In the user's content model inside Contentful, setting a validation to enforce this (GenAI output may vary in length, in spite of prompts to the contrary) will ensure output conforming to Google's SEO guidelines.

**Comment by aruby-atlas** [comment]
Hi @allanwhite 

You might consider setting the value at the lower end of the range, since ChatGPT doesn't really understand character counts all that well. 

In our testing, we achieved a higher success rate for meeting the character limit using 100 vs 150 characters in the prompt. (We tested using the **Prompt** option and pasted both a modified prompt and source content as input.)

**Comment by whitelisab** [comment]
This issue was addressed in this PR: #8900
